default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: kkait0713
  password: "Kaito0713"
  pool: 5

development:
  <<: *default
  database: online_voting_app_development

test:
  <<: *default
  database: online_voting_app_test

production:
  <<: *default
  database: online_voting_app_production
  username: online_voting_app
  password: <%= ENV['ONLINE_VOTING_APP_DATABASE_PASSWORD'] %>
